declare const __MOZILLA_BYO_AI_GRAMMAR_API_KEY__: string;

export const BUILD_TIME_API_KEY_NAME = "MOZILLA_BYO_AI_GRAMMAR_API_KEY";
export const BUILD_TIME_API_KEY = __MOZILLA_BYO_AI_GRAMMAR_API_KEY__;
